################################################################
## MANDATORY PARAMETERS
##
  description: ""
  author: "Claire Rioualen and Jacques van Helden"
  author_email: ""
  title: "FNR analysis protocol for RNA-seq data"
  dataset: "GSE41195"
  qsub: "-V -m a -d ." 
  genome:
    organism: "Escherichia coli K12 MG1655"
    version: "Ecoli_K12"
    size: "4639221"
    fasta_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.dna.chromosome.Chromosome.fa
    gff3_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.chromosome.Chromosome.gff3
    gtf_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.gtf

  metadata:
    samples: "metadata/samples_RNA-seq.tab"                            # required. has to contain at least sample ids
    design: "metadata/design_RNA-seq.tab"                              # required. has to contain at least ids of pairs of samples to be compared
    configfile: "metadata/config_RNA-seq.yml"                          # required for flowcharts generation; maybe this should be revised
    seq_type: "pe"                                                                                  # required
    strands: "1 2"
    input_format: "fastq.gz"                                            # Optional. If not specified, will be "fastq.gz" by default.

  dir:
    reads_source: "data"                                                # Raw data (sra)
    fastq: "RNA-seq/fastq"                                                      # Fastq location, either raw data or converted sra files 
    genome: "genome"                                                    # Location of the genome files (fasta, gff3, gtf) or symlink to location
    results: "RNA-seq/results"
    snakechunks: "SnakeChunks"                                          # Location of the library or symlink to library

    samples: "RNA-seq/results/samples"
    diffexpr: "RNA-seq/results/diffexpr"
    reports: "RNA-seq/results/reports"

  trimming: "cutadapt"
  mapping: "bwa"
  read_counts: "featureCounts"
  diffexpr: "DESeq2"

  mapping_wf:
    snakefile: "mapping.wf"
    configfile: "metadata/config_RNA-seq.yml"

################################################################
## OPTIONAL PARAMETERS
##
## These are the parameters that are used by rules & programs. 
##
## If nothing is mentionned  below, all prgrams will use their default parameters. 
  sickle:
    qual_threshold: 20                                                # Quality threshold. Default 20
    length_threshold: 20                                              # Minimal output read length. Default 20

  cutadapt:
    qual_threshold: 20                                                # Quality threshold. Default 20
    length_threshold: 20                                              # Minimal output read length. Default 20

  bwa:
    threads: 1             # Number of threads (parallel computing) for bwa

  subread-align:
    threads: "1"                                                         ## Number of threads

  hisat2:
    threads: "1"                                                         ## Number of threads

  tophat:
    threads: "1"                                                         ## Number of threads

  STAR:
    threads: "1"                                                         ## Number of threads

  bowtie2:
    threads: "1"                                                         ## Number of threads
    mode: "--local"                                                         # Alignent mode. Supported: "--local" or "--end-to-end"
    other_options: "--very-fast --maxins 1500"                                 # supplementary options. We should evaluate if we do not convert them to fully documented options

  subread-featureCounts:
    attr_type: "gene_id"                                                # Default 'gene_id'
    feature_type: "exon"                                                # Default "exon"
    strand_specificity: 1                                               # Strand-specific read counting, 0 (unstranded)(default), 1 (stranded) or 2 (reversely stranded)
    multi_mapping: ""


  DEG:                        ## Generic parameters for differential analysis
    epsilon: 0.1
    check_sample_ids: FALSE    # Check consistency of sample IDs between count table and sample description file
    reorder_samples: "counts"  # Reorder samples of the count table to match the rows of the the sample description table. Supported: "counts","sample_desc", "none"
    pAdjustMethod: "BH"       # Default "BH", else "BY"
    alpha: 0.05               # Default 0.05
    rowsum_filter: 10         # Default 10
    selection_criterion: "union"  # Criterion to select DEG. Supported: DESeq2 | edgeR | intersection | union
    blacklist: "" ## a tab-separated value file with IDs of specific features to filter out (in the first column, other columns are ignored).
    norm_method: ["DESeq2", "TMM"]
    norm_percentile: 75       # Percentile for the "upperquartile" normalisation, that will be converted to a quantile for edgeR::calcNormFactors().
    thresholds:               # Thresholds for feature filtering + detection of differentially expressed genes (apply to DESeq2 and edgeR)
      min.count: 0            # Filter out features whose min count is smaller than the specified value. Note that this means a single  inferior count in a single sample is sufficient to discard the whole row
      max.count: 500000       # Filter out outlier features, i.e. those with several hundred thousands counts
      mean.count: 5           # Filter out features with very low mean expression level
      min.var: 25             # Filter out features with very low variance
      mean.per.condition: 10  # Filter out features for which not a single condition has a mean count above the threshold
      padj: 0.05              # Upper threshold on False Discovery Rate (FDR)
      FC: 2                   # Lower threshold on the fold-change (will be applied in both orientations)

  DESeq2:
    pAdjustMethod: "BH"       # Default "BH", else "BY"
    alpha: 0.05               # Default 0.05
    rowsum_filter: 10         # Default 10
  
  edgeR:
    pAdjustMethod: "BH"       # Default "BH", else "BY"
    alpha: 0.05               # Default 0.05
    rowsum_filter: 10         # Default 10
    norm_method: ["TMM"]
    
#  DEG:                                                             ## Generic parameters for differential analysis
#    epsilon: 0.1
#    pAdjustMethod: "BH"                                                 # Default "BH", else "BY"
#    alpha: 0.05                                                         # Default 0.05
#    rowsum_filter: 10                                                   # Default 10
#    selection_criterion: "intersection"                                       # Criterion to select DEG. Supported: DESeq2 | edgeR | intersection | union
#    thresholds:                                  ## Thresholds tor fhte detection of differentially expressed genes (apply to DESeq2 and edgeR)
#      min.count: 1  ## Filter out undetected features
#      mean.count: 5  ## Filter out features with very low mean expression level
#      mean.per.condition: 10  ## Filter out features for which not a single condition has a mean count above the threshold
#      padj: 0.05                                 ## Upper threshold on False Discovery Rate (FDR)
#      FC: 1.14                                    ## Lower threshold on the fold-change
#      max.log10.cpm: 8.5                         ## Upper threshold for outliers on log10-transformed counts
 
                                                
#  DESeq2:
#    pAdjustMethod: "BH"                                                 # Default "BH", else "BY"
#    alpha: 0.05                                                         # Default 0.05
#    rowsum_filter: 10                                                   # Default 10
#    featuresToRemove: NULL                                              # "alignment_not_unique", "ambiguous", "no_feature", "not_aligned", "too_low_aQual"
#    varInt: "group"
#    condRef: "WT"
#    batch: NULL
#    fitType: "parametric"                                               # "parametric" (default) or "local"
#    cooksCutoff: TRUE
#    independentFiltering: TRUE
#    alpha: 0.05
#    pAdjustMethod: "BH"                                                 # "BH" (default) or "BY"
#    typeTrans: "VST"                                                    # "VST" or "rlog"
#    locfunc: "median"                                                   # "median" (default) or "shorth" to estimate the size factors



