################################################################
## GENERAL PARAMETERS
##
  description: ""
  author: "Claire Rioualen and Jacques van Helden"
  title: "FNR analysis protocol for ChIP-seq data"
  dataset: "GSE41195"
  qsub: "-V -m a -d ." 
  genome:
    organism: "Escherichia coli K12 MG1655"
    version: "Ecoli_K12"
    size: "4639221"
    fasta_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.dna.chromosome.Chromosome.fa
    gff3_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.chromosome.Chromosome.gff3
    gtf_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.gtf

  metadata:
    samples: "metadata/samples_ChIP-seq.tab"                            # Required. Has to contain at least an "ID" column. 
    design: "metadata/design_ChIP-seq.tab"                              # Required. Has to contain at least ids of pairs of samples to be compared
    configfile: "metadata/config_ChIP-seq.yml"                          # Required for flowcharts generation; maybe this should be revised
    seq_type: "se"                                                      # Required
    input_format: "fastq.gz"                                            # Optional. If not specified, will be "fastq.gz" by default.
    TF: "FNR"                                                           # List of transcription factors of interest. Required for RegulonDB comparison. 

  dir:
    reads_source: ""
    fastq: "ChIP-seq/fastq"
    genome: "genome"                                                    # Required. Directory containing the genome of references, annotations, and genoms indexes.
    results: "ChIP-seq/results"                                         # Required. Directory containing all result files that are produced by the pipeline
    snakechunks: "SnakeChunks"                                          # Required. Location of the SnakeChunks library

    samples: "ChIP-seq/results/samples"                                 # Optional. will hold sample treatment (trimming, alignment, QC...).    If not mentioned, will be config["dir"]["results"]
    peaks: "ChIP-seq/results/peaks"                                     # Optional. will hold the results of differential expression analysis. If not mentioned, will be config["dir"]["results"]
    reports: "ChIP-seq/results/reports"                                 # Optional. will hold reports and graphics.                             If not mentioned, will be config["dir"]["results"]
    regulondb: "data/RegulonDB"

################################################################
## WORKFLOW DESIGN
##
  trimming: "cutadapt"
  mapping: "bowtie2"
  peakcalling: "homer macs2"

################################################################
## OPTIONAL PARAMETERS
##
## Parameters used by rules & programs.
## If nothing is mentionned  below, all programs will use their default parameters.
  cutadapt:
    qual_threshold: "20"                                                # Optional (def. 20)
    length_threshold: "20"                                              # Optional (def. 20)

  bowtie2:
    threads: "2"                                                        # Number of threads
#    mode: "--local"                                                     # Alignent mode. Supported: "--local" or "--end-to-end"
#    other_options: "--very-fast"                                        # supplementary options. We should evaluate if we do not convert them to fully documented options
    
  macs2: 
    qval: "0.05"                                                        # Optional (def. 0.05)
    keep_dup: "all"                                                     # Optional (def. 1)
    mfold_min: "2"                                                      # Optional (def. 5)
    mfold_max: "50"                                                     # Optional (def. 50)
    other_options: "--nomodel"                                          # Optional can include --call-summits, --broad...

  homer: 
    style: "factor"                                                     # Optional (def. factor), can be factor, histone, groseq, tss, dnase, super, mC (beware of output filenames)
    F: "2"                                                              # Optional (def. 4)
    L: "2"                                                              # Optional (def. 4)
    P: "0.01"                                                           # Optional (def. 0.0001)
    fdr: "0.01"                                                         # Optional (def. 0.001)


