################################################################
## GENERAL PARAMETERS
##
  description: ""
  author: "Claire Rioualen and Jacques van Helden"
  title: "FNR analysis protocol for data integration"
  dataset: "GSE41195"
  qsub: "-V -m a -d ." 
  genome:
    organism: "Escherichia coli K12 MG1655"
    version: "Ecoli_K12"
    size: "4639221"
    fasta_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.dna.chromosome.Chromosome.fa
    gff3_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.chromosome.Chromosome.gff3
    gtf_file: Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.37.gtf

  metadata:
    samples: "metadata/samples_ChIP-seq.tab"                            # Required. Has to contain at least an "ID" column. 
    design: "metadata/design_ChIP-seq.tab"                              # Required. Has to contain at least ids of pairs of samples to be compared
    configfile: "metadata/config_integration.yml"                          # Required for flowcharts generation; maybe this should be revised
    seq_type: "se"                                                      # Required
    input_format: "fastq.gz"                                            # Optional. If not provided, will be "fastq".
    TF: "FNR"                                                           # List of transcription factors of interest. Required for RegulonDB comparison. 

  dir:
    fastq: "ChIP-seq/fastq"
    genome: "genome"                                                    # Required. Directory containing the genome of references, annotations, and genoms indexes.
    results: "ChIP-seq/results"                                         # Required. Directory containing all result files that are produced by the pipeline
    snakechunks: "SnakeChunks"                                          # Required. Location of the SnakeChunks library

    samples: "ChIP-seq/results/samples"                                 # Optional. will hold sample treatment (trimming, alignment, QC...).    If not mentioned, will be config["dir"]["results"]
    peaks: "ChIP-seq/results/peaks"                                     # Optional. will hold the results of differential expression analysis. If not mentioned, will be config["dir"]["results"]
    diffexpr: "RNA-seq/results/diffexpr"                                 # Optional. will hold reports and graphics.                             If not mentioned, will be config["dir"]["results"]
    regulondb: "data/RegulonDB"

################################################################
## WORKFLOW DESIGN
##
  trimming: "cutadapt"
  mapping: "bwa"
  peakcalling: "homer macs2"
  read_counts: "featureCounts"
  diffexpr: "DESeq2"

